Repository seoul-night/ddubam-server, pull requests merged in 2024-06, with the labels that each got.

#65 fix/64 near trail
  src/main/java/growthook/org/bamgang/trail/domain/Trail.java
  src/main/java/growthook/org/bamgang/trail/service/TrailServiceImpl.java
Labels: fix

#76 feat: #75- 도착지 후기 추가 구현 완료
  src/main/java/growthook/org/bamgang/members/controller/MemberController.java
  src/main/java/growthook/org/bamgang/members/domain/FinishedDestination.java
  src/main/java/growthook/org/bamgang/members/dto/request/FinishedDestinationRequest.java
  src/main/java/growthook/org/bamgang/members/repository/DataFinishedDestintationRepository.java
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
  src/main/java/growthook/org/bamgang/members/service/SpringConfig.java
Labels: feat, 🟠 높음

#78 feat: #77- 후기 리스트 조회 구현 완료
  src/main/java/growthook/org/bamgang/members/controller/MemberController.java
  src/main/java/growthook/org/bamgang/members/dto/response/GetFinishedDestinationResponseDto.java
  src/main/java/growthook/org/bamgang/members/repository/DataFinishedDestintationRepository.java
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
Labels: feat, 🟠 높음

#60 feat/57 인터셉터 추가
  src/main/java/growthook/org/bamgang/config/WebmvcConfig.java
  src/main/java/growthook/org/bamgang/global/auth/config/AuthorizationInterceptor.java
  src/main/java/growthook/org/bamgang/members/dto/token/MemberToken.java
  src/main/java/growthook/org/bamgang/members/jwtUtil/JWTUtil.java
Labels: feat, 🟠 높음

#87 Fix/86 cors error
  src/main/java/growthook/org/bamgang/config/WebmvcConfig.java
  src/main/java/growthook/org/bamgang/global/auth/config/AuthorizationInterceptor.java
  src/main/java/growthook/org/bamgang/members/controller/MemberController.java
Labels: fix, 🔴 긴급

#92 fix: #90-완료한 산책로 리스트 조회 수정
  src/main/java/growthook/org/bamgang/members/service/MemberService.java
Labels: fix, 🔴 긴급

#94 fix: #93-인기 산책로 시설물 type추가 완료
  src/main/java/growthook/org/bamgang/trail/dto/response/GetPopularTrailResponseDto.java
  src/main/java/growthook/org/bamgang/trail/service/TrailServiceImpl.java
Labels: fix, 🟠 높음
